### ISSUE TITLE
Creating NetBox superuser fails on NetBox 4.0

### ISSUE THREAD

**Issue by sleinen** [lae/ansible-role-netbox#179]
After installing NetBox 4.0.0 or 4.0.1, the super-user creation script fails with the following error:
```
Traceback (most recent call last):
  File "/srv/netbox/current/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/netbox/current/venv-py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/netbox/current/venv-py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/netbox/current/venv-py3/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/netbox/current/venv-py3/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/netbox/current/venv-py3/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 4, in <module>
  File "/srv/netbox/current/venv-py3/lib/python3.11/site-packages/django/db/models/manager.py", line 196, in __get__
    raise AttributeError(
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'users.User'
```

**Comment by lae** [comment]
Merged your 4.0 related PRs. If there's anything else you think needs to be added, I'll leave a few days buffer for new issues, otherwise I'll try to remember to cut a new minor release for these changes later in the week.
