### ISSUE TITLE
Issue when Postgresql is a remote server

### ISSUE THREAD

**Issue by dcardellino** [lae/ansible-role-netbox#80]
I try to install netbox with a remote postgresql database server on ubuntu 18.04.
My Playbook Looks like this:
`
---
- hosts: all
  become: yes
  roles:
    - davidwittman.redis
    - lae.netbox
  vars:
    netbox_stable: true
    netbox_stable_version: 2.7.9
netbox_database_host: <RemotePostgres IP-Address>
    netbox_database_port: 5432
    netbox_database_conn_age: 300

    netbox_config:
      ALLOWED_HOSTS:
        - 127.0.0.1
        - localhost
      # note that the array is nested above
      MEDIA_ROOT: '{{ netbox_shared_path }}/media'
      REPORTS_ROOT: '{{ netbox_shared_path }}/reports'
      SCRIPTS_ROOT: '{{ netbox_shared_path }}/scripts'
redis_bind: 127.0.0.1
`

At the task Run database migrations for NetBox i receive the following error:
`
:stderr: Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/db/utils.py", line 216, in all
    return [self[alias] for alias in self]
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/netbox/current/venv-py3/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/netbox/releases/netbox-2.7.9/netbox/netbox/settings.py", line 163, in <module>
    "REDIS section in configuration.py is missing webhooks subsection."
django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing webhooks subsection.
`

If i do the installation on a single host or a vagrant box (All on one host postgres, redis and netbox) everything works fine.

Can you please help me?

**Comment by pugnacity** [comment]
Currently only netbox 2.6.X is supported, see also #67

**Comment by dcardellino** [comment]
Great, with 2.6.12 it is working. Thank you!
